package main
import("encoding/json";"fmt";"log";"os";"os/signal";"strings";"syscall";"github.com/bwmarrin/discordgo")
type Config struct{Prefix string; Verification struct{Enabled bool; ChannelId,RoleId,Emoji,Title,Description string}; Tickets struct{Enabled bool; PanelChannelId,CategoryId,SupportRoleId,Emoji,Title,Description string}}
var cfg Config
func mustConfig(){b,err:=os.ReadFile("config.json"); if err!=nil{fmt.Println("[Maszynka] Skończ mnie konfigurować w config.json. Skopiuj config.example.json jako config.json."); os.Exit(1)}; if strings.Contains(string(b),"PUT_"){fmt.Println("[Maszynka] Skończ mnie konfigurować w config.json. W pliku nadal są placeholdery PUT_..._HERE."); os.Exit(1)}; json.Unmarshal(b,&cfg); if cfg.Prefix==""{cfg.Prefix="m!"}}
func main(){token:=os.Getenv("DISCORD_TOKEN"); if token==""{fmt.Println("DISCORD_TOKEN is not configured"); os.Exit(1)}; mustConfig(); s,err:=discordgo.New("Bot "+token); if err!=nil{log.Fatal(err)}; s.Identify.Intents=discordgo.IntentsGuilds|discordgo.IntentsGuildMessages|discordgo.IntentsGuildMessageReactions|discordgo.IntentsGuildMembers|discordgo.IntentsMessageContent
s.AddHandler(func(s *discordgo.Session,r *discordgo.Ready){log.Println("[Maszynka] Logged in as",s.State.User.String()); log.Println("[Maszynka] Prefix commands ready:",cfg.Prefix+"help",cfg.Prefix+"weryfikacja",cfg.Prefix+"ticket",cfg.Prefix+"configcheck")})
s.AddHandler(func(s *discordgo.Session,m *discordgo.MessageCreate){if m.Author.Bot||!strings.HasPrefix(m.Content,cfg.Prefix){return}; cmd:=strings.Fields(strings.TrimPrefix(m.Content,cfg.Prefix)); if len(cmd)==0{return}; switch cmd[0]{case"help": s.ChannelMessageSend(m.ChannelID,"Komendy: `"+cfg.Prefix+"weryfikacja`, `"+cfg.Prefix+"ticket`, `"+cfg.Prefix+"configcheck`"); case"weryfikacja": msg,_:=s.ChannelMessageSend(m.ChannelID,"**"+cfg.Verification.Title+"**\n"+cfg.Verification.Description); s.MessageReactionAdd(m.ChannelID,msg.ID,cfg.Verification.Emoji); case"ticket": msg,_:=s.ChannelMessageSend(m.ChannelID,"**"+cfg.Tickets.Title+"**\n"+cfg.Tickets.Description); s.MessageReactionAdd(m.ChannelID,msg.ID,cfg.Tickets.Emoji); case"configcheck": s.ChannelMessageSend(m.ChannelID,"Config wygląda poprawnie. Bot jest gotowy do pracy.")}})
s.AddHandler(func(s *discordgo.Session,r *discordgo.MessageReactionAdd){if r.UserID==s.State.User.ID{return}; if cfg.Verification.Enabled&&r.Emoji.Name==cfg.Verification.Emoji&&r.ChannelID==cfg.Verification.ChannelId{s.GuildMemberRoleAdd(r.GuildID,r.UserID,cfg.Verification.RoleId); log.Println("[Maszynka] Zweryfikowano użytkownika",r.UserID)}; if cfg.Tickets.Enabled&&r.Emoji.Name==cfg.Tickets.Emoji&&r.ChannelID==cfg.Tickets.PanelChannelId{ch,_:=s.GuildChannelCreateComplex(r.GuildID,discordgo.GuildChannelCreateData{Name:"ticket-"+r.UserID,Type:discordgo.ChannelTypeGuildText,ParentID:cfg.Tickets.CategoryId}); s.ChannelMessageSend(ch.ID,"<@"+r.UserID+"> <@&"+cfg.Tickets.SupportRoleId+">\nTicket utworzony. Opisz swój problem."); log.Println("[Maszynka] Utworzono ticket",ch.ID)}})
if err=s.Open();err!=nil{log.Fatal(err)}; stop:=make(chan os.Signal,1); signal.Notify(stop,syscall.SIGINT,syscall.SIGTERM); <-stop; s.Close()}
